version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8000"
    command: sh -c "/code/entrypoint.sh"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db_data:
  static:

